added severity
reload/github-security-jira pull request #153
Opened 2022-01-24 18:15 UTC by cr-alan

#### What does this PR do?
This adds severity to the Title of the jira

#### Where should the reviewer start?
Only 2 lines were added/changed in SecurityAlertIssue.php

#### How can the reviewer see this in action?

#### Any background context you want to provide?
Severity is a critical component for prioritization.  This deserves a place in the title.  

#### Is this related to processing of personal data?
No

#### What are the relevant tickets?

#### Screenshots (if appropriate)

#### Questions for the reviewer:

2022-01-26 08:59 UTC, carlossless commented
Would love to see this introduced! :)

2022-01-26 10:17 UTC, achton commented on README.md
> +- `JIRA_LABELS`: Jira labels to add to tickets. Separate multiple labels with comma (no spaces).
```suggestion
- `JIRA_ISSUE_LABELS`: Jira labels to add to tickets. Separate multiple labels with comma (no spaces).
```

2022-02-10 21:08 UTC, cr-alan commented
Curious to see if this will get merged in?

2022-02-11 12:40 UTC, xendk requested changes
Basically looks good. I've let phpcs and phpstan run, and there's a few style issues to fix. I've summarized them in comments.

2022-02-11 12:40 UTC, xendk commented on src/SecurityAlertIssue.php
> +
```suggestion

        foreach (\explode(',', $labels) as $label) {
            $this->setKeyLabel($label);
        }
```

2022-02-11 12:40 UTC, xendk commented on src/SecurityAlertIssue.php
> +        foreach (\explode(',', $labels) as $label){
`getenv()` might return `false` if the variable doesn't exist, so you should wrap the foreach in a `if ($labels) {`.

2022-02-11 12:40 UTC, xendk commented on src/SecurityAlertIssue.php
> +        $this->severity = $data['securityVulnerability']['severity'];
Please define the property in the section above.

2022-02-17 02:11 UTC, drchiodo commented
up

2022-02-22 13:24 UTC, xendk commented
OK, one PHPCS notice left. I'll merge and fix it afterwards.

2022-02-22 13:24 UTC, merged